### ISSUE TITLE
Buttons too high compared to the navbar

### ISSUE THREAD

**Issue by odmfl** [yassineAbou/Calculator#1]
hi, thank you for this app I really like it. I find the keys (numbers) too high and uncomfortable to press, there is too much space between the navbar and the numbers, please could you lower everything downwards like in all other calculators?

**Comment by yassineAbou** [comment]
If I'm understanding you correctly, the numbers should be next to the bottom system navigation bar, and there should be no space between them
<img src="https://github.com/user-attachments/assets/f5b4e738-048f-40f6-8f8c-7d3c5b030f65" alt="drawing" width="300"/>

**Comment by odmfl** [comment]
> If I'm understanding you correctly, the numbers should be next to the bottom system navigation bar, and there should be no space between them <img alt="drawing" width="300" src="https://private-user-images.githubusercontent.com/72861602/378232501-f5b4e738-048f-40f6-8f8c-7d3c5b030f65.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTg5NTEsIm5iZiI6MTcyOTQ5ODY1MSwicGF0aCI6Ii83Mjg2MTYwMi8zNzgyMzI1MDEtZjViNGU3MzgtMDQ4Zi00MGY2LThmOGMtN2QzYzViMDMwZjY1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA4MTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNmZkNGExZTliMWI5ZTJlNTk2YjE1MDkyMzgxMTk3NjM1NGM4MmQwOTdmMWQ5YjNlY2FmMjI1ZmM1NmVjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b8eX07U4CVd0Yb_JDUEe9oyGDRPiqlYK6HsjS8tUXo4">

Yes that's exactly what I mean, that space should be eliminated

**Comment by yassineAbou** [comment]
I'm going to work on fixing the issue. Once it's fixed, I'll add the APK version to the repository. You can then try it out and give me your feedback. After that, I'll update the Play Store app and upload the app to F-Droid. I'll let you know when the APK version is available in the repository.

**Comment by odmfl** [comment]
Thanks ❤️

**Comment by yassineAbou** [comment]
The APK is available in the releases section of the repository. You can try it out.

**Comment by odmfl** [comment]
I tried the apk it looks like this on my phone, maybe if you can raise it a few millimeters it would be perfect. I ask you if you can add this in the file
themes.xml because as you can see the navigation bar is black and the status bar does not have the same color as the background, adding this code solves it.

<item name="android:statusBarColor" >?attr/colorOnPrimary</item>
<item name="android:windowLightNavigationBar">true</item>
<item name="android:navigationBarColor">@android:color/white</item>

![144D794C-219C-4EF4-99C9-5F8D6A296B14](https://github.com/user-attachments/assets/16b71214-93f9-414b-981b-63d974ad793e)

**Comment by odmfl** [comment]
In themes.xml

<item name="android:statusBarColor" >?attr/colorOnPrimary</item>

<item name="android:windowLightNavigationBar">true</item>

<item name="android:navigationBarColor">@android:color/white</item>

**Comment by yassineAbou** [comment]
The numbers are raised up by a few millimeters as you said. You can check the new version. I don't think I need to change the color of the system nav bar because the solution is actually easier

**Comment by odmfl** [comment]
> The numbers are raised up by a few millimeters as you said. You can check the new version. I don't think I need to change the color of the system nav bar because the solution is actually easier

Yes now it's perfect. Thank you so much

**Comment by yassineAbou** [comment]
You're welcome 😊
